export const PERMISSION_CATALOG = [
  { resource: 'income', action: 'read' },
  { resource: 'income', action: 'read', scope: 'OWN' as const },
  { resource: 'income', action: 'create' },
  { resource: 'income', action: 'create', scope: 'OWN' as const },
  { resource: 'income', action: 'update' },
  { resource: 'income', action: 'update', scope: 'OWN' as const },
  { resource: 'income', action: 'delete' },
  { resource: 'income', action: 'delete', scope: 'OWN' as const },
  { resource: 'expense', action: 'read' },
  { resource: 'expense', action: 'read', scope: 'OWN' as const },
  { resource: 'expense', action: 'create' },
  { resource: 'expense', action: 'create', scope: 'OWN' as const },
  { resource: 'expense', action: 'update' },
  { resource: 'expense', action: 'update', scope: 'OWN' as const },
  { resource: 'expense', action: 'delete' },
  { resource: 'expense', action: 'delete', scope: 'OWN' as const },
  { resource: 'account', action: 'read' },
  { resource: 'account', action: 'read', scope: 'OWN' as const },
  { resource: 'account', action: 'create' },
  { resource: 'account', action: 'create', scope: 'OWN' as const },
  { resource: 'account', action: 'update' },
  { resource: 'account', action: 'update', scope: 'OWN' as const },
  { resource: 'account', action: 'delete' },
  { resource: 'account', action: 'delete', scope: 'OWN' as const },
  { resource: 'tax', action: 'read' },
  { resource: 'tax', action: 'create' },
  { resource: 'tax', action: 'update' },
  { resource: 'tax', action: 'delete' },
  { resource: 'user', action: 'read' },
  { resource: 'user', action: 'create' },
  { resource: 'user', action: 'update' },
  { resource: 'user', action: 'delete' },
  { resource: 'user', action: 'assign_role' },
  { resource: 'role', action: 'read' },
  { resource: 'role', action: 'create' },
  { resource: 'role', action: 'update' },
  { resource: 'role', action: 'delete' },
  { resource: 'permission', action: 'read' },
  { resource: 'shopify_connection', action: 'create' },
  { resource: 'shopify_connection', action: 'create', scope: 'OWN' as const },
  { resource: 'shopify_connection', action: 'read' },
  { resource: 'shopify_connection', action: 'read', scope: 'OWN' as const },
  { resource: 'shopify_connection', action: 'delete' },
  { resource: 'shopify_connection', action: 'delete', scope: 'OWN' as const },
  { resource: 'shopify_connection', action: 'update' },
  { resource: 'shopify_connection', action: 'update', scope: 'OWN' as const },
  { resource: 'expense_category', action: 'read' },
  { resource: 'expense_category', action: 'read', scope: 'OWN' as const },
  { resource: 'expense_category', action: 'create' },
  { resource: 'expense_category', action: 'create', scope: 'OWN' as const },
  { resource: 'expense_category', action: 'update' },
  { resource: 'expense_category', action: 'update', scope: 'OWN' as const },
  { resource: 'expense_category', action: 'delete' },
  { resource: 'expense_category', action: 'delete', scope: 'OWN' as const },
  { resource: 'cogs', action: 'read' },
  { resource: 'cogs', action: 'read', scope: 'OWN' as const },
  { resource: 'cogs', action: 'create' },
  { resource: 'cogs', action: 'create', scope: 'OWN' as const },
  { resource: 'cogs', action: 'update' },
  { resource: 'cogs', action: 'update', scope: 'OWN' as const },
  { resource: 'cogs', action: 'delete' },
  { resource: 'cogs', action: 'delete', scope: 'OWN' as const },
  { resource: 'employee', action: 'read' },
  { resource: 'employee', action: 'read', scope: 'OWN' as const },
  { resource: 'employee', action: 'create' },
  { resource: 'employee', action: 'create', scope: 'OWN' as const },
  { resource: 'employee', action: 'update' },
  { resource: 'employee', action: 'update', scope: 'OWN' as const },
  { resource: 'employee', action: 'delete' },
  { resource: 'employee', action: 'delete', scope: 'OWN' as const },
  { resource: 'payroll', action: 'read' },
  { resource: 'payroll', action: 'read', scope: 'OWN' as const },
  { resource: 'payroll', action: 'create' },
  { resource: 'payroll', action: 'create', scope: 'OWN' as const },
  { resource: 'payroll', action: 'update' },
  { resource: 'payroll', action: 'update', scope: 'OWN' as const },
  { resource: 'payroll', action: 'delete' },
  { resource: 'payroll', action: 'delete', scope: 'OWN' as const },
  { resource: 'tax_payment', action: 'read' },
  { resource: 'tax_payment', action: 'read', scope: 'OWN' as const },
  { resource: 'tax_payment', action: 'create' },
  { resource: 'tax_payment', action: 'create', scope: 'OWN' as const },
  { resource: 'tax_payment', action: 'update' },
  { resource: 'tax_payment', action: 'update', scope: 'OWN' as const },
  { resource: 'tax_payment', action: 'delete' },
  { resource: 'tax_payment', action: 'delete', scope: 'OWN' as const },
  { resource: 'report', action: 'read' },
  { resource: 'report', action: 'read', scope: 'OWN' as const },
  { resource: 'product_cost', action: 'read' },
  { resource: 'product_cost', action: 'read', scope: 'OWN' as const },
  { resource: 'product_cost', action: 'create' },
  { resource: 'product_cost', action: 'create', scope: 'OWN' as const },
  { resource: 'product_cost', action: 'update' },
  { resource: 'product_cost', action: 'update', scope: 'OWN' as const },
  { resource: 'product_cost', action: 'delete' },
  { resource: 'product_cost', action: 'delete', scope: 'OWN' as const },
  { resource: 'product_category_override', action: 'read' },
  {
    resource: 'product_category_override',
    action: 'read',
    scope: 'OWN' as const,
  },
  { resource: 'product_category_override', action: 'create' },
  {
    resource: 'product_category_override',
    action: 'create',
    scope: 'OWN' as const,
  },
  { resource: 'product_category_override', action: 'update' },
  {
    resource: 'product_category_override',
    action: 'update',
    scope: 'OWN' as const,
  },
  { resource: 'product_category_override', action: 'delete' },
  {
    resource: 'product_category_override',
    action: 'delete',
    scope: 'OWN' as const,
  },
  { resource: 'recurring_expense', action: 'read' },
  { resource: 'recurring_expense', action: 'read', scope: 'OWN' as const },
  { resource: 'recurring_expense', action: 'create' },
  { resource: 'recurring_expense', action: 'create', scope: 'OWN' as const },
  { resource: 'recurring_expense', action: 'update' },
  { resource: 'recurring_expense', action: 'update', scope: 'OWN' as const },
  { resource: 'recurring_expense', action: 'delete' },
  { resource: 'recurring_expense', action: 'delete', scope: 'OWN' as const },
  { resource: 'payable', action: 'read' },
  { resource: 'payable', action: 'read', scope: 'OWN' as const },
  { resource: 'payable', action: 'create' },
  { resource: 'payable', action: 'create', scope: 'OWN' as const },
  { resource: 'payable', action: 'update' },
  { resource: 'payable', action: 'update', scope: 'OWN' as const },
  { resource: 'payable', action: 'delete' },
  { resource: 'payable', action: 'delete', scope: 'OWN' as const },
  { resource: 'receivable', action: 'read' },
  { resource: 'receivable', action: 'read', scope: 'OWN' as const },
  { resource: 'receivable', action: 'create' },
  { resource: 'receivable', action: 'create', scope: 'OWN' as const },
  { resource: 'receivable', action: 'update' },
  { resource: 'receivable', action: 'update', scope: 'OWN' as const },
  { resource: 'receivable', action: 'delete' },
  { resource: 'receivable', action: 'delete', scope: 'OWN' as const },
  { resource: 'monthly_close', action: 'read' },
  { resource: 'monthly_close', action: 'read', scope: 'OWN' as const },
  { resource: 'monthly_close', action: 'update' },
  { resource: 'monthly_close', action: 'update', scope: 'OWN' as const },
  { resource: 'invitation', action: 'create' },
  { resource: 'invitation', action: 'read' },
  { resource: 'invitation', action: 'delete' },
] as const;

export type PermissionString = (typeof PERMISSION_CATALOG)[number] extends {
  resource: infer R;
  action: infer A;
}
  ? `${R & string}:${A & string}`
  : never;
